### PR TITLE
Romanian translation for strings.xml

### PR DESCRIPTION
**Pull request by VVLADII**

### CODE REVIEW

**Comment by Lambada10** [comment]
You're not supposed to change original strings.xml, instead make a file in language-specific values folder (`res/values-XX/strings.xml` where XX is country code)

**Comment by nift4** [comment]
or use weblate thats easier XD
(manually changing translations won't break it btw, but anyway)

**Comment by nift4** [comment]
why close, it was correct

**Comment by VVLADII** [comment]
ugh lambada said to make values-ro folder so ive did that, gonna pull another request with right folders and stuff

**Comment by Lambada10** [comment]
It updated here as well though

**Pull request closed without merging**
